version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
