apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: {{ .Values.image }}
          env:
            - name: REACT_APP_NAME_COLOR 
              value: {{ .Values.color }}
          ports:
            - containerPort: 3000
